spring.main.banner-mode=off
logging.level.root=INFO
allocation.lottery.seed=1357911
app.streams.replication-factor=3
app.streams.num-standby-replicas=1
app.failed-t-topic=failed-t-events
app.s-with-q-carry-topic=s-with-q-carry-events
