spring:
  main:
    banner-mode: "off"
  kafka:
    bootstrap-servers: localhost:9093
    properties:
      security.protocol: SSL
      ssl.endpoint.identification.algorithm: HTTPS
      ssl.truststore.location: ""
      ssl.truststore.password: ""
      ssl.keystore.location: ""
      ssl.keystore.password: ""
      ssl.key.password: ""
      schema.registry.url: https://localhost:8081
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ""
      schema.registry.ssl.truststore.location: ""
      schema.registry.ssl.truststore.password: ""
      schema.registry.ssl.keystore.location: ""
      schema.registry.ssl.keystore.password: ""
      schema.registry.ssl.key.password: ""

logging:
  level:
    root: INFO

allocation:
  lottery:
    seed: 1357911

app:
  application-id: stateful-data-processor
  input-topic: input-events
  output-topic: processed-events
  db-sync-topic: db-sync-events
  failed-t-topic: failed-t-events
  s-with-q-carry-topic: s-with-q-carry-events
  recon-report-topic: recon-report-events
  state-dir: processor/kafka-streams-state
  commit-interval-ms: 100
  streams:
    replication-factor: 3
    num-standby-replicas: 1
  kafka:
    security-protocol: SSL
